#
# Copyright 2024 tosit.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: publish helm chart into oci registry

on:
  workflow_call:
    inputs:
      path:
        description: Package path
        required: true
        type: string
      chart_name:
        description: Helm chart version
        required: true
        type: string
      version:
        description: Helm chart version
        required: true
        type: string
      git_tag_name:
        description: Github released tag name
        required: true
        type: string
  
env:
  chart_package_name: ${{ inputs.chart_name }}-${{ inputs.version }}.tgz
  cr_release_name_template: "{{ .Name }}-v{{ .Version }}"

defaults:
  run:
    shell: bash
  
jobs:

  helm-chart-publish:
    name: "Helm publish (${{ inputs.chart_name }}-${{ inputs.version }})"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout release tag ${{ inputs.git_tag_name }} ⚡️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_tag_name }}
      
      - name: Update release title
        run: |
          gh release edit ${{ inputs.git_tag_name }} --title="${{ inputs.chart_name }}-helm-chart-${{ inputs.version }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Setup helm 📦
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.1

      - name: Add chart dependencies 📦
        run: |
          helm repo add superset https://apache.github.io/superset
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Install chart-releaser (cr) 📦
        uses: helm/chart-releaser-action@v1.6.0
        with:
          install_only: true

      - name: Package helm chart ${{ inputs.path }} (${{ inputs.version }}) 📦
        run: |
          helm dependency build ${{ inputs.path }}
          cr package ${{ inputs.path }}
    
      - name: Set up oci charts registry 📦
        id: registry
        run:  |
            echo "registry=${{ vars.REGISTRY || 'quay.io' }}" >> $GITHUB_OUTPUT
            echo "registry_repo=${{ vars.REGISTRY || 'quay.io' }}/${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
     
      # More secure than helm registry login
      - name: Login into ${{ steps.registry.outputs.registry }} oci charts registry 🔐
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.registry.outputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_ROBOT_TOKEN }}

      # - name: Install Cosign 📦
      #   uses: sigstore/cosign-installer@v3.5.0

      # - name: Check cosign install! 📦
      #   run: cosign version

      - name: Push chart ${{ env.chart_package_name }} to oci registry  📤
        run: |
            helm push ./.cr-release-packages/${{ env.chart_package_name }} \
              oci://${{ steps.registry.outputs.registry_repo }}/charts

      - name: Upload Chart ${{ env.chart_package_name }} package to Github release  📤
        run: |
          gh release upload ${{ inputs.git_tag_name }} ./.cr-release-packages/${{ env.chart_package_name }} --clobber
        env:
          GH_TOKEN: ${{ github.token }}

      # - name: Checkout gh-pages branch  ⚡️
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      #     ref: gh-pages
      #     path: gh-pages

      # - name: Update helm chart index.yaml
      #   run: |
      #     cr index  -i gh-pages/index.yaml \
      #               -r ${GITHUB_REPOSITORY#*/} \
      #               -o ${{ github.repository_owner }} \
      #               --release-name-template "${{ env.cr_release_name_template }}"
      #   shell: bash

      # - name: Commit helm chart index.yaml changes into gh-pages branch
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     cwd: gh-pages
      #     pull: "--rebase --autostash"
      #     message: '[${{ inputs.chart_name }}-${{ inputs.version }}] - Update index.yaml'
      #     author_name: github-actions[bot]
      #     author_email: 41898282+github-actions[bot]@users.noreply.github.com
