#
# Copyright 2024 tosit.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: ci 

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:

  helm-lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
  
      - name: Run chart-testing (list-changed) ✅
        id: list-changed
        run: |
            changed=$(ct list-changed --config .ct.yml)
            if [[ -n "$changed" ]]; then
              echo "list_changed=$(echo ${changed} | tr -d \')" >> "$GITHUB_OUTPUT"
              echo "changed=true" >> "$GITHUB_OUTPUT"
            fi
  
      - name: Run chart-testing (lint) ✅
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config .ct.yml --check-version-increment=false --print-config
  
      - name: Free up disk space 🧹
        if: steps.list-changed.outputs.changed == 'true'
        uses: idirze/workflows/.github/actions/free-disk-space@main

      - name: Set up kind cluster ✅
        if: steps.list-changed.outputs.changed == 'true'
        uses: idirze/workflows/.github/actions/setup-kind@main

      - name: Run chart-testing (install) ✅
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --config .ct.yml --print-config

      - name: Install helm-docs
        uses: idirze/workflows/.github/actions/helm-docs@main

      - name: Generate helm docs
        run: |
          echo "Generate docs from charts"
          helm-docs -c .

      - name: Commit helm docs changes
        # Github token from forked repo does not have permission to push to target repo
        # Skip the step for PRs from forked repos
        if: |
            ${{ ((github.event_name == 'push') || (github.event_name == 'pull_request'
                  && github.event.pull_request.head.repo.full_name == github.repository)) }}
        uses: EndBug/add-and-commit@v9
        with:
          pull: "--rebase --autostash"
          add: "**/README.md"
          message: '[helm-docs] Update readme'
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com

